apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-project.fullname" . }}-config
  labels:
    {{- include "devops-project.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.app.environment | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
