{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devops-project.fullname" . }}-app
  labels:
    {{- include "devops-project.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "devops-project.fullname" . }}-app
                port:
                  number: {{ .Values.app.service.port }}
{{- end }}
