{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "devops-project.fullname" . }}-app
  labels:
    {{- include "devops-project.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "devops-project.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
