apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-project

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - app.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

secretGenerator:
  - name: app-secrets
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
